name: Generate Snake Game

on:
  push:
    branches:
      - main
  schedule:
    - cron: "0 0 * * *"

jobs:
  build:
    runs-on: ubuntu-latest
    env:
      ACTIONS_STEP_DEBUG: true

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Generate Snake Game
        uses: Platane/snk@v2
        with:
          github_user_name: yamangokhan
          outputs: dist/snake.svg

      - name: Push Snake Animation
        uses: crazy-max/ghaction-github-pages@v2.6.0
        with:
          target_branch: main
          build_dir: dist

