name: Generate Snake Game

on:
  push:
    branches:
      - main
  schedule:
    - cron: "0 0 * * *" # Günlük olarak çalıştırır

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout the repository
        uses: actions/checkout@v3

      - name: Generate Snake Game from GitHub Contributions
        uses: Platane/snk@v2
        with:
          github_user_name: yamangokhan # Kullanıcı adınızı buraya yazın
          outputs: dist/snake.svg

      - name: Push Snake Animation to GitHub
        uses: crazy-max/ghaction-github-pages@v2.6.0
        with:
          target_branch: output
          build_dir: dist
