name: Generate contribution snake

on:
  schedule:               # Her gün gece 00:00'da çalışır
    - cron: "0 0 * * *"
  workflow_dispatch:      # Manuel olarak "Run workflow" ile çalıştırılabilir

permissions:
  contents: write

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Generate Snake
        uses: Platane/snk@v3
        with:
          github_user_name: yamangokhan     # 🔹 senin GitHub kullanıcı adın
          outputs: dist/snake.svg
          theme: github-dark
          format: svg

      - name: Push Snake to output branch
        uses: crazy-max/ghaction-github-pages@v4
        with:
          target_branch: output
          build_dir: dist
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
